# Generated by Django 4.0 on 2021-12-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myfiles', '0003_sotib_olingan_maxsulotlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=30)),
                ('tel', models.CharField(max_length=20)),
                ('matn', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Murojatlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=30)),
                ('tel', models.CharField(max_length=20)),
                ('matn', models.TextField()),
            ],
        ),
    ]
